# Generated by Django 5.0.7 on 2024-09-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='key',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
