# Generated by Django 5.0.7 on 2024-08-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custodian',
            old_name='user',
            new_name='email',
        ),
    ]
