# Generated by Django 5.0.7 on 2024-09-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0002_state_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='key',
            new_name='intials',
        ),
    ]
