# Generated by Django 5.0.7 on 2024-08-20 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0003_rename_user_custodian_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodian',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank', to='app_bank.bank'),
        ),
    ]
