# Generated by Django 5.0.7 on 2024-11-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0005_state_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['id']},
        ),
    ]
