# Generated by Django 5.0.7 on 2024-12-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0006_alter_bank_options_alter_state_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
