# Generated by Django 5.0.7 on 2024-08-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0006_alter_custodian_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodian',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
