# Generated by Django 5.0.7 on 2024-08-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0007_custodian_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custodian',
            name='is_deleted',
        ),
    ]
