# Generated by Django 5.0.7 on 2024-08-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
