# Generated by Django 5.0.7 on 2024-09-29 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_fault', '0002_initial'),
        ('app_inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentnames', to='app_inventory.componentname'),
        ),
        migrations.AddField(
            model_name='part',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='part',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partnames', to='app_inventory.partname'),
        ),
        migrations.AddField(
            model_name='requestcomponent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentapprovedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestcomponent',
            name='fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentfault', to='app_fault.fault'),
        ),
        migrations.AddField(
            model_name='requestcomponent',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestcomponents', to='app_inventory.componentname'),
        ),
        migrations.AddField(
            model_name='requestcomponent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentrequestuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestpart',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partapprovedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestpart',
            name='fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partfault', to='app_fault.fault'),
        ),
        migrations.AddField(
            model_name='requestpart',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestparts', to='app_inventory.partname'),
        ),
        migrations.AddField(
            model_name='requestpart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partrequestuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unconfirmedpart',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unconfirmedpart',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temppartnames', to='app_inventory.partname'),
        ),
        migrations.AddField(
            model_name='unconfirmedpart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
