# Generated by Django 5.0.7 on 2024-10-10 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_fault', '0002_initial'),
        ('app_inventory', '0003_remove_unconfirmedpart_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcomponent',
            name='fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentfault', to='app_fault.fault'),
        ),
        migrations.AlterField(
            model_name='requestpart',
            name='fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partfault', to='app_fault.fault'),
        ),
    ]
