# Generated by Django 5.0.7 on 2024-10-19 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0004_alter_requestcomponent_fault_alter_requestpart_fault'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unconfirmedpart',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unconfirmedpart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partpostedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
