# Generated by Django 5.0.7 on 2024-11-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0005_alter_unconfirmedpart_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='componentname',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='partname',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='requestcomponent',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='requestpart',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='unconfirmedpart',
            options={'ordering': ['id']},
        ),
    ]
