# Generated by Django 5.0.7 on 2025-01-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0007_unconfirmedpart_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unconfirmedpart',
            name='name',
        ),
    ]
