# Generated by Django 5.0.7 on 2025-01-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0008_remove_unconfirmedpart_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unconfirmedpart',
            old_name='name2',
            new_name='name',
        ),
    ]
