# Generated by Django 5.0.7 on 2025-01-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0009_rename_name2_unconfirmedpart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
