# Generated by Django 5.0.7 on 2025-01-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0010_component_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='action',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
