# Generated by Django 5.0.7 on 2025-01-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0011_alter_component_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='action',
        ),
        migrations.AddField(
            model_name='component',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
