# Generated by Django 5.0.7 on 2025-01-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0012_remove_component_action_component_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
