# Generated by Django 5.0.7 on 2025-01-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0013_alter_component_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='status',
        ),
        migrations.AddField(
            model_name='component',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
