# Generated by Django 5.0.7 on 2025-01-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0014_remove_component_status_component_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
