# Generated by Django 5.0.7 on 2024-12-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chatroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='contactMessage',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='youMessage',
        ),
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
