# Generated by Django 5.0.7 on 2024-12-21 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_chatroom', '0002_remove_chat_contactmessage_remove_chat_youmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'contact'], name='user_contact_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['contact', 'user'], name='contact_user_idx'),
        ),
    ]
