# Generated by Django 5.0.7 on 2024-08-07 12:21

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/', null=True, upload_to=app_users.models.unique_profile_pic),
        ),
    ]
