# Generated by Django 5.0.7 on 2024-10-07 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_engineer_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
