# Generated by Django 5.0.7 on 2024-10-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_engineer_engineer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineer',
            old_name='engineer',
            new_name='branch_engineer',
        ),
    ]
