# Generated by Django 5.0.7 on 2024-10-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_rename_engineer_engineer_branch_engineer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineer',
            old_name='branch_engineer',
            new_name='engineer',
        ),
    ]
