# Generated by Django 5.0.7 on 2024-10-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_rename_branch_engineer_engineer_engineer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deliveries',
        ),
    ]
