# Generated by Django 5.0.7 on 2024-10-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_engineerassignmentnotificaion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerassignmentnotificaion',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
