# Generated by Django 5.0.7 on 2024-10-16 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_location', '0009_alter_location_location'),
        ('app_users', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerassignmentnotificaion',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newlocation', to='app_location.location'),
        ),
        migrations.AlterField(
            model_name='engineerassignmentnotificaion',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
