# Generated by Django 5.0.7 on 2024-10-17 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0005_state_region'),
        ('app_custodian', '0018_delete_requestdetailschange'),
        ('app_location', '0009_alter_location_location'),
        ('app_users', '0014_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateUserAndBranchNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationIsNew', models.BooleanField(default=False)),
                ('newBank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatebank', to='app_bank.bank')),
                ('newBranch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatebranch', to='app_custodian.branch')),
                ('newCustodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatecustodian', to='app_custodian.custodian')),
                ('newLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatelocation', to='app_location.location')),
                ('newRegion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updateregion', to='app_users.region')),
                ('newState', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updatestate', to='app_bank.state')),
            ],
        ),
    ]
