# Generated by Django 5.0.7 on 2024-10-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_updateuserandbranchnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateuserandbranchnotification',
            name='locationIsNew',
        ),
        migrations.AlterField(
            model_name='updateuserandbranchnotification',
            name='newBank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='updateuserandbranchnotification',
            name='newBranch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='updateuserandbranchnotification',
            name='newCustodian',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='updateuserandbranchnotification',
            name='newLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='updateuserandbranchnotification',
            name='newRegion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='updateuserandbranchnotification',
            name='newState',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
