# Generated by Django 5.0.7 on 2024-10-17 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0016_remove_updateuserandbranchnotification_locationisnew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='updateuserandbranchnotification',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='updateuserandbranchnotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
