# Generated by Django 5.0.7 on 2024-10-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0017_updateuserandbranchnotification_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateuserandbranchnotification',
            old_name='user',
            new_name='requestUser',
        ),
    ]
