# Generated by Django 5.0.7 on 2024-10-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0018_rename_user_updateuserandbranchnotification_requestuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdateUserAndBranchNotification',
            new_name='UpdateLocationAndBranchNotification',
        ),
    ]
