# Generated by Django 5.0.7 on 2024-11-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0019_rename_updateuserandbranchnotification_updatelocationandbranchnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='engineerassignmentnotificaion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='updatelocationandbranchnotification',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
    ]
