# Generated by Django 5.0.7 on 2024-11-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0020_alter_engineer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerassignmentnotificaion',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
