# Generated by Django 5.0.7 on 2024-11-03 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0022_remove_engineerassignmentnotificaion_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatelocationandbranchnotification',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='updatelocationandbranchnotification',
            name='approved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='updatelocationandbranchnotification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='updatelocationandbranchnotification',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
