# Generated by Django 5.0.7 on 2024-09-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('feature', models.CharField(max_length=100)),
                ('benefit', models.CharField(max_length=100)),
                ('conclusion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_images', models.ImageField(upload_to='product_images/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=500)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='app_products.description')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=500)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='app_products.description')),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='app_products.product'),
        ),
    ]
