# Generated by Django 5.0.7 on 2024-08-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='app_products.description'),
        ),
    ]
