# Generated by Django 5.0.7 on 2024-08-07 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0003_alter_product_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='description',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='app_products.product'),
        ),
    ]
