# Generated by Django 5.0.7 on 2024-08-07 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0005_alter_description_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='app_products.product'),
        ),
    ]
