# Generated by Django 5.0.7 on 2024-09-29 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_custodian', '0003_initial'),
        ('app_fault', '0001_initial'),
        ('app_location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignedto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fault',
            name='confirm_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fault',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faultlocation', to='app_location.location'),
        ),
        migrations.AddField(
            model_name='fault',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loggedby', to='app_custodian.custodian'),
        ),
        migrations.AddField(
            model_name='fault',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fault',
            name='supervised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fault',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faults', to='app_fault.faultname'),
        ),
    ]
