# Generated by Django 5.0.7 on 2024-10-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fault', '0003_remove_fault_confirm_by_fault_confirmed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault',
            name='resolved_by',
        ),
    ]
