# Generated by Django 5.0.7 on 2024-10-11 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fault', '0006_rename_resolved_by_fault_replacement_engineer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault',
            name='replacement_engineer',
        ),
    ]
