# Generated by Django 5.0.7 on 2024-11-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_fault', '0008_fault_replacement_engineer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fault',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='faultname',
            options={'ordering': ['id']},
        ),
    ]
