# Generated by Django 5.0.7 on 2024-12-29 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custodian', '0023_remove_branch_custodian'),
        ('app_fault', '0009_alter_fault_options_alter_faultname_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fault',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='faultbranch', to='app_custodian.branch'),
        ),
    ]
