# Generated by Django 5.0.7 on 2024-10-01 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0005_state_region'),
        ('app_location', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banklocations', to='app_bank.bank'),
        ),
    ]
