# Generated by Django 5.0.7 on 2024-10-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_location', '0003_location_bank'),
        ('app_users', '0002_rename_date_of_birth_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regionlocations', to='app_users.region'),
        ),
    ]
