# Generated by Django 5.0.7 on 2024-10-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0005_state_region'),
        ('app_location', '0005_remove_location_bank_location_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='bank',
            field=models.ManyToManyField(blank=True, related_name='banklocations', to='app_bank.bank'),
        ),
    ]
