# Generated by Django 5.0.7 on 2024-11-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_location', '0011_location_location2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location2',
        ),
    ]
