# Generated by Django 5.0.7 on 2024-11-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_location', '0012_remove_location_location2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
