# Generated by Django 5.0.7 on 2024-09-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_custodian', '0001_initial'),
        ('app_location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locationbranches', to='app_location.location'),
        ),
        migrations.AddField(
            model_name='custodian',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custodiansbranch', to='app_custodian.branch'),
        ),
    ]
