# Generated by Django 5.0.7 on 2024-09-29 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_custodian', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='custodian',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='custodiandata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestdetailschange',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requestuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
