# Generated by Django 5.0.7 on 2024-09-29 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bank', '0004_rename_intials_state_initial'),
        ('app_custodian', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statebranches', to='app_bank.state'),
        ),
    ]
