# Generated by Django 5.0.7 on 2024-10-07 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custodian', '0004_branch_state'),
        ('app_users', '0005_alter_engineer_engineer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custodian',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchcustodian', to='app_custodian.custodian'),
        ),
        migrations.AddField(
            model_name='branch',
            name='engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchengineer', to='app_users.engineer'),
        ),
    ]
