# Generated by Django 5.0.7 on 2024-10-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_custodian', '0007_rename_custodian_custodian_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custodian',
            old_name='email',
            new_name='custodian',
        ),
    ]
