# Generated by Django 5.0.7 on 2024-10-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_custodian', '0008_rename_email_custodian_custodian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custodian',
            old_name='custodian',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='requestdetailschange',
            old_name='email',
            new_name='user',
        ),
    ]
