# Generated by Django 5.0.7 on 2024-10-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custodian', '0011_rename_user_custodian_custodian'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodian',
            name='test',
            field=models.CharField(default='heyo', max_length=10),
        ),
    ]
