# Generated by Django 5.0.7 on 2024-10-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_custodian', '0012_custodian_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='engineer',
            new_name='branch_engineer',
        ),
    ]
