# Generated by Django 5.0.7 on 2024-10-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_custodian', '0014_rename_user_requestdetailschange_custodian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custodian',
            name='test',
        ),
    ]
