# Generated by Django 5.0.7 on 2024-10-13 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custodian', '0015_remove_custodian_test'),
        ('app_users', '0008_remove_user_deliveries'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branchregion', to='app_users.region'),
        ),
    ]
