# Generated by Django 5.0.7 on 2024-10-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_custodian', '0017_alter_branch_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestDetailsChange',
        ),
    ]
