# Generated by Django 5.0.7 on 2024-11-03 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_custodian', '0019_alter_branch_options_alter_custodian_options'),
        ('app_users', '0023_updatelocationandbranchnotification_approve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branchengineer', to='app_users.engineer'),
        ),
    ]
