# Generated by Django 5.0.7 on 2024-12-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_custodian', '0022_alter_branch_bank_alter_branch_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='custodian',
        ),
    ]
