# Generated by Django 5.0.7 on 2025-01-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_custodian', '0024_branch_custodian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='custodian',
        ),
    ]
